// =========================================================================
// SGIP PLACEMENT ROADMAP - STAGE 1: APTITUDE ROADMAP (36 TOPICS / 6 PHASES)
// =========================================================================

export const PLACEMENT_ROADMAP_STAGES = [
  { id: 1, name: 'Aptitude', status: 'ACTIVE', desc: 'Quantitative, Logical, DI & Verbal Foundation' },
  { id: 2, name: 'Technical Skills', status: 'LOCKED', desc: 'Core CS Fundamentals (OS, CN, OOPs)' },
  { id: 3, name: 'DSA & Coding', status: 'LOCKED', desc: 'Data Structures, Algorithms & LeetCode Practice' },
  { id: 4, name: 'SQL & Database', status: 'LOCKED', desc: 'Queries, Normalization, Indexing & Schemas' },
  { id: 5, name: 'Projects', status: 'LOCKED', desc: 'Full Stack & AI/ML Capstone Repositories' },
  { id: 6, name: 'Communication', status: 'LOCKED', desc: 'Group Discussions, JAM & Business English' },
  { id: 7, name: 'Mock Tests', status: 'LOCKED', desc: 'Company-specific Assessment Simulators' },
  { id: 8, name: 'Technical Interview', status: 'LOCKED', desc: 'System Design & Deep Dive Problem Solving' },
  { id: 9, name: 'HR Interview', status: 'LOCKED', desc: 'Behavioral, STAR Method & Cultural Fit' },
  { id: 10, name: 'Placement Ready', status: 'LOCKED', desc: 'Top Tier Product & Service Company Offers' },
];

export const APTITUDE_PHASES = [
  {
    id: 1,
    title: 'Phase 1 – Basic Mathematics',
    desc: 'Core fundamentals of numbers, factors, fractions, and proportions.',
    category: 'Quantitative Aptitude',
    topicCount: 6,
    icon: 'Calculator',
  },
  {
    id: 2,
    title: 'Phase 2 – Arithmetic',
    desc: 'Commercial math, speed, time, work, and interest calculations.',
    category: 'Quantitative Aptitude',
    topicCount: 6,
    icon: 'TrendingUp',
  },
  {
    id: 3,
    title: 'Phase 3 – Advanced Arithmetic',
    desc: 'Complex problem-solving with combinations, probability, and mixtures.',
    category: 'Quantitative Aptitude',
    topicCount: 5,
    icon: 'Layers',
  },
  {
    id: 4,
    title: 'Phase 4 – Data Interpretation',
    desc: 'Visual data analytics, bar charts, pie diagrams, and caselets.',
    category: 'Data Interpretation',
    topicCount: 5,
    icon: 'BarChart3',
  },
  {
    id: 5,
    title: 'Phase 5 – Logical Reasoning',
    desc: 'Analytical thinking, patterns, family trees, and seating deductions.',
    category: 'Logical Reasoning',
    topicCount: 8,
    icon: 'Brain',
  },
  {
    id: 6,
    title: 'Phase 6 – Verbal Ability',
    desc: 'Grammar mastery, reading comprehension, vocabulary, and sentence ordering.',
    category: 'Verbal Ability',
    topicCount: 6,
    icon: 'BookOpen',
  },
];

export const INITIAL_APTITUDE_TOPICS = [
  // ==========================================
  // PHASE 1: BASIC MATHEMATICS (6 Topics)
  // ==========================================
  {
    topicId: 'p1_num_sys',
    phase: 1,
    phaseTitle: 'Phase 1 – Basic Mathematics',
    category: 'Quantitative Aptitude',
    topicName: 'Number System',
    difficulty: 'Easy',
    estimatedTime: '45 min',
    prerequisites: [],
    progress: 100,
    completed: true,
    questionsSolved: 30,
    totalQuestions: 30,
    quizScore: 92,
    lastAttempt: '2026-08-25',
    description: 'Classifications of real numbers, prime tests, unit digits, cyclicity, and divisibility rules.',
    videoLinks: {
      tamil: 'https://www.youtube.com/watch?v=g-_xCXSVv1w',
      english: 'http://www.youtube.com/playlist?list=PLpyc33gOcbVA4qXMoQ5vmhefTruk5t9lt',
    },
    shortcuts: [
      'Divisibility by 3 and 9: Sum of digits is divisible by 3 or 9.',
      'Divisibility by 11: (Sum of odd-position digits) - (Sum of even-position digits) = 0 or 11k.',
      'Sum of first n natural numbers = n(n + 1)/2. Sum of first n odd numbers = n².',
    ],
  },
  {
    topicId: 'p1_hcf_lcm',
    phase: 1,
    phaseTitle: 'Phase 1 – Basic Mathematics',
    category: 'Quantitative Aptitude',
    topicName: 'HCF & LCM',
    difficulty: 'Easy',
    estimatedTime: '45 min',
    prerequisites: ['p1_num_sys'],
    progress: 100,
    completed: true,
    questionsSolved: 25,
    totalQuestions: 25,
    quizScore: 88,
    lastAttempt: '2026-08-25',
    description: 'Prime factorization, bells tolling together, remainder conditions, and fraction HCF/LCM.',
    videoLinks: {
      tamil: 'https://www.youtube.com/watch?v=RGOvOpQo8cY',
      english: 'http://www.youtube.com/playlist?list=PLpyc33gOcbVA4qXMoQ5vmhefTruk5t9lt',
    },
    shortcuts: [
      'Product of two numbers = HCF × LCM.',
      'HCF of fractions = HCF(numerators) / LCM(denominators).',
      'Bells ringing together = LCM of interval seconds.',
    ],
  },
  {
    topicId: 'p1_simplification',
    phase: 1,
    phaseTitle: 'Phase 1 – Basic Mathematics',
    category: 'Quantitative Aptitude',
    topicName: 'Simplification',
    difficulty: 'Easy',
    estimatedTime: '40 min',
    prerequisites: ['p1_hcf_lcm'],
    progress: 100,
    completed: true,
    questionsSolved: 20,
    totalQuestions: 20,
    quizScore: 85,
    lastAttempt: '2026-08-26',
    description: 'BODMAS rules, algebraic identities, surds, indices, and fast square root techniques.',
    videoLinks: {
      tamil: 'http://www.youtube.com/playlist?list=PL1lPSVzW89HbDUfnF-h7uoeP73vsPeZyj',
      english: 'http://www.youtube.com/playlist?list=PLpyc33gOcbVA4qXMoQ5vmhefTruk5t9lt',
    },
    shortcuts: [
      'BODMAS: Brackets, Orders, Division, Multiplication, Addition, Subtraction.',
      '(a + b)² - (a - b)² = 4ab.',
      '[(a + b)² + (a - b)²] / (a² + b²) = 2.',
    ],
  },
  {
    topicId: 'p1_percentages',
    phase: 1,
    phaseTitle: 'Phase 1 – Basic Mathematics',
    category: 'Quantitative Aptitude',
    topicName: 'Percentages',
    difficulty: 'Medium',
    estimatedTime: '50 min',
    prerequisites: ['p1_simplification'],
    progress: 80,
    completed: false,
    questionsSolved: 24,
    totalQuestions: 30,
    quizScore: 80,
    lastAttempt: '2026-08-26',
    description: 'Fraction conversion tables, percentage increase/decrease, successive changes, and population depreciation.',
    videoLinks: {
      tamil: 'http://www.youtube.com/playlist?list=PL1lPSVzW89Hb9OB0BVOKAgya76G1ID5-k',
      english: 'http://www.youtube.com/playlist?list=PLpyc33gOcbVA4qXMoQ5vmhefTruk5t9lt',
    },
    shortcuts: [
      'Fraction Cheat: 1/2=50%, 1/3=33.3%, 1/4=25%, 1/5=20%, 1/6=16.67%, 1/7=14.28%, 1/8=12.5%.',
      'Net Change = (a + b + ab/100)%.',
      'If A is r% more than B, B is [r / (100 + r)] × 100% less than A.',
    ],
  },
  {
    topicId: 'p1_ratio_prop',
    phase: 1,
    phaseTitle: 'Phase 1 – Basic Mathematics',
    category: 'Quantitative Aptitude',
    topicName: 'Ratio & Proportion',
    difficulty: 'Medium',
    estimatedTime: '45 min',
    prerequisites: ['p1_percentages'],
    progress: 70,
    completed: false,
    questionsSolved: 18,
    totalQuestions: 25,
    quizScore: 75,
    lastAttempt: '2026-08-26',
    description: 'Compounded ratios, duplicate ratios, mean proportional, coin problems, and income-expenditure splits.',
    videoLinks: {
      tamil: 'http://www.youtube.com/playlist?list=PL1lPSVzW89HbDUfnF-h7uoeP73vsPeZyj',
      english: 'http://www.youtube.com/playlist?list=PLpyc33gOcbVA4qXMoQ5vmhefTruk5t9lt',
    },
    shortcuts: [
      'Mean proportional of a and b = √(a × b).',
      'Third proportional to a and b = b² / a.',
      'Fourth proportional to a, b, c = (b × c) / a.',
    ],
  },
  {
    topicId: 'p1_average',
    phase: 1,
    phaseTitle: 'Phase 1 – Basic Mathematics',
    category: 'Quantitative Aptitude',
    topicName: 'Average',
    difficulty: 'Easy',
    estimatedTime: '40 min',
    prerequisites: ['p1_ratio_prop'],
    progress: 50,
    completed: false,
    questionsSolved: 10,
    totalQuestions: 20,
    quizScore: 70,
    lastAttempt: '2026-08-27',
    description: 'Arithmetic mean, weighted averages, replacement problem shortcuts, and batsman inning averages.',
    videoLinks: {
      tamil: 'http://www.youtube.com/playlist?list=PL1lPSVzW89HZSU-2nTJm47pt8GveJBjAE',
      english: 'http://www.youtube.com/playlist?list=PLpyc33gOcbVA4qXMoQ5vmhefTruk5t9lt',
    },
    shortcuts: [
      'Average = Sum of items / Number of items.',
      'New person weight = Replaced weight ± (Change in avg × Total count).',
      'Average speed for equal distances = 2xy / (x + y).',
    ],
  },

  // ==========================================
  // PHASE 2: ARITHMETIC (6 Topics)
  // ==========================================
  {
    topicId: 'p2_profit_loss',
    phase: 2,
    phaseTitle: 'Phase 2 – Arithmetic',
    category: 'Quantitative Aptitude',
    topicName: 'Profit & Loss',
    difficulty: 'Medium',
    estimatedTime: '55 min',
    prerequisites: ['p1_percentages'],
    progress: 40,
    completed: false,
    questionsSolved: 12,
    totalQuestions: 30,
    quizScore: 65,
    lastAttempt: '2026-08-27',
    description: 'CP, SP, marked price, trade discounts, dishonest dealer false weights, and successive discount chains.',
    videoLinks: {
      tamil: 'http://www.youtube.com/playlist?list=PL1lPSVzW89HbDUfnF-h7uoeP73vsPeZyj',
      english: 'http://www.youtube.com/playlist?list=PLpyc33gOcbVA4qXMoQ5vmhefTruk5t9lt',
    },
    shortcuts: [
      'Gain % = (Gain / CP) × 100.',
      'When two items sold at same SP, one at x% gain and other at x% loss: Net loss = (x/10)² %.',
      'Dishonest dealer gain % = [Error / (True - Error)] × 100.',
    ],
  },
  {
    topicId: 'p2_simple_interest',
    phase: 2,
    phaseTitle: 'Phase 2 – Arithmetic',
    category: 'Quantitative Aptitude',
    topicName: 'Simple Interest',
    difficulty: 'Easy',
    estimatedTime: '40 min',
    prerequisites: ['p1_percentages'],
    progress: 30,
    completed: false,
    questionsSolved: 6,
    totalQuestions: 20,
    quizScore: 60,
    lastAttempt: '2026-08-27',
    description: 'PTR/100 interest formula, amount doubling shortcuts, and alligation methods for split investments.',
    videoLinks: {
      tamil: 'http://www.youtube.com/playlist?list=PL1lPSVzW89HYTitAcAMUT6UjBWgia1eKn',
      english: 'http://www.youtube.com/playlist?list=PLpyc33gOcbVA4qXMoQ5vmhefTruk5t9lt',
    },
    shortcuts: [
      'SI = (P × R × T) / 100.',
      'If sum doubles in T years: Rate R = 100 / T.',
      'T2 = T1 × (m - 1) / (n - 1).',
    ],
  },
  {
    topicId: 'p2_compound_interest',
    phase: 2,
    phaseTitle: 'Phase 2 – Arithmetic',
    category: 'Quantitative Aptitude',
    topicName: 'Compound Interest',
    difficulty: 'Hard',
    estimatedTime: '55 min',
    prerequisites: ['p2_simple_interest'],
    progress: 20,
    completed: false,
    questionsSolved: 5,
    totalQuestions: 25,
    quizScore: 50,
    lastAttempt: null,
    description: 'Annual & half-yearly compounding, 2-year difference formula, 3-year difference formula, and population doubling.',
    videoLinks: {
      tamil: 'http://www.youtube.com/playlist?list=PL1lPSVzW89HYTitAcAMUT6UjBWgia1eKn',
      english: 'http://www.youtube.com/playlist?list=PLpyc33gOcbVA4qXMoQ5vmhefTruk5t9lt',
    },
    shortcuts: [
      '2-Year Difference: Diff = P × (R/100)².',
      '3-Year Difference: Diff = P × (R/100)² × (3 + R/100).',
      'If sum doubles in T years at CI, it becomes 8 times in 3T years.',
    ],
  },
  {
    topicId: 'p2_time_work',
    phase: 2,
    phaseTitle: 'Phase 2 – Arithmetic',
    category: 'Quantitative Aptitude',
    topicName: 'Time & Work',
    difficulty: 'Medium',
    estimatedTime: '50 min',
    prerequisites: ['p1_ratio_prop'],
    progress: 40,
    completed: false,
    questionsSolved: 10,
    totalQuestions: 25,
    quizScore: 55,
    lastAttempt: null,
    description: 'LCM unit work method, worker efficiency ratios, alternate day cycles, and man-day formula.',
    videoLinks: {
      tamil: 'http://www.youtube.com/playlist?list=PL1lPSVzW89HbDUfnF-h7uoeP73vsPeZyj',
      english: 'http://www.youtube.com/playlist?list=PLpyc33gOcbVA4qXMoQ5vmhefTruk5t9lt',
    },
    shortcuts: [
      'Total Work = LCM of days. Time = Work / Combined Efficiency.',
      'M1 × D1 × H1 / W1 = M2 × D2 × H2 / W2.',
    ],
  },
  {
    topicId: 'p2_pipes_cisterns',
    phase: 2,
    phaseTitle: 'Phase 2 – Arithmetic',
    category: 'Quantitative Aptitude',
    topicName: 'Pipes & Cisterns',
    difficulty: 'Medium',
    estimatedTime: '45 min',
    prerequisites: ['p2_time_work'],
    progress: 25,
    completed: false,
    questionsSolved: 5,
    totalQuestions: 20,
    quizScore: 50,
    lastAttempt: null,
    description: 'Inlet filling rates, outlet emptying rates, tank leak calculations, and alternating pipe openings.',
    videoLinks: {
      tamil: 'http://www.youtube.com/playlist?list=PL1lPSVzW89HbDUfnF-h7uoeP73vsPeZyj',
      english: 'http://www.youtube.com/playlist?list=PLpyc33gOcbVA4qXMoQ5vmhefTruk5t9lt',
    },
    shortcuts: [
      'Inlet = positive efficiency (+), Outlet/Leak = negative efficiency (-).',
      'Filling Time = Tank Capacity / Net Efficiency.',
    ],
  },
  {
    topicId: 'p2_time_speed_distance',
    phase: 2,
    phaseTitle: 'Phase 2 – Arithmetic',
    category: 'Quantitative Aptitude',
    topicName: 'Time, Speed & Distance',
    difficulty: 'Hard',
    estimatedTime: '60 min',
    prerequisites: ['p1_average'],
    progress: 30,
    completed: false,
    questionsSolved: 9,
    totalQuestions: 30,
    quizScore: 60,
    lastAttempt: null,
    description: 'Relative speed in trains, crossing platforms, average speed, and police-thief chases.',
    videoLinks: {
      tamil: 'http://www.youtube.com/playlist?list=PL1lPSVzW89HbDUfnF-h7uoeP73vsPeZyj',
      english: 'http://www.youtube.com/playlist?list=PLpyc33gOcbVA4qXMoQ5vmhefTruk5t9lt',
    },
    shortcuts: [
      'km/h to m/s = Multiply by 5/18. m/s to km/h = Multiply by 18/5.',
      'Relative speed: Same direction (u - v), Opposite direction (u + v).',
      'Train passing platform: Dist = L_train + L_platform.',
    ],
  },

  // ==========================================
  // PHASE 3: ADVANCED ARITHMETIC (5 Topics)
  // ==========================================
  {
    topicId: 'p3_problems_ages',
    phase: 3,
    phaseTitle: 'Phase 3 – Advanced Arithmetic',
    category: 'Quantitative Aptitude',
    topicName: 'Problems on Ages',
    difficulty: 'Easy',
    estimatedTime: '35 min',
    prerequisites: ['p1_ratio_prop'],
    progress: 0,
    completed: false,
    questionsSolved: 0,
    totalQuestions: 20,
    quizScore: 0,
    lastAttempt: null,
    description: 'Past, present, and future age ratio equations, age differences, and linear algebraic modeling.',
    videoLinks: {
      tamil: 'http://www.youtube.com/playlist?list=PL1lPSVzW89HbDUfnF-h7uoeP73vsPeZyj',
      english: 'http://www.youtube.com/playlist?list=PLpyc33gOcbVA4qXMoQ5vmhefTruk5t9lt',
    },
    shortcuts: [
      'Age difference between two persons remains constant across all years.',
      'Use cross-multiplication on ratio changes over t years.',
    ],
  },
  {
    topicId: 'p3_partnership',
    phase: 3,
    phaseTitle: 'Phase 3 – Advanced Arithmetic',
    category: 'Quantitative Aptitude',
    topicName: 'Partnership',
    difficulty: 'Medium',
    estimatedTime: '40 min',
    prerequisites: ['p1_ratio_prop'],
    progress: 0,
    completed: false,
    questionsSolved: 0,
    totalQuestions: 20,
    quizScore: 0,
    lastAttempt: null,
    description: 'Simple and compound partnerships, active working partners, and profit ratios proportional to capital × time.',
    videoLinks: {
      tamil: 'http://www.youtube.com/playlist?list=PL1lPSVzW89HbDUfnF-h7uoeP73vsPeZyj',
      english: 'http://www.youtube.com/playlist?list=PLpyc33gOcbVA4qXMoQ5vmhefTruk5t9lt',
    },
    shortcuts: [
      'Profit Ratio = (Capital_A × Time_A) : (Capital_B × Time_B).',
    ],
  },
  {
    topicId: 'p3_mixtures_alligations',
    phase: 3,
    phaseTitle: 'Phase 3 – Advanced Arithmetic',
    category: 'Quantitative Aptitude',
    topicName: 'Mixtures & Allegations',
    difficulty: 'Hard',
    estimatedTime: '50 min',
    prerequisites: ['p1_ratio_prop'],
    progress: 0,
    completed: false,
    questionsSolved: 0,
    totalQuestions: 25,
    quizScore: 0,
    lastAttempt: null,
    description: 'Alligation cross rule, mixing liquids of varied concentrations, and repeated replacement formulas.',
    videoLinks: {
      tamil: 'http://www.youtube.com/playlist?list=PL1lPSVzW89HbDUfnF-h7uoeP73vsPeZyj',
      english: 'http://www.youtube.com/playlist?list=PLpyc33gOcbVA4qXMoQ5vmhefTruk5t9lt',
    },
    shortcuts: [
      '(Cheaper Quantity) / (Dearer Quantity) = (Dearer Price - Mean) / (Mean - Cheaper Price).',
      'Remaining pure liquid = Initial × (1 - x / V)^n.',
    ],
  },
  {
    topicId: 'p3_permutation_comb',
    phase: 3,
    phaseTitle: 'Phase 3 – Advanced Arithmetic',
    category: 'Quantitative Aptitude',
    topicName: 'Permutation & Combination',
    difficulty: 'Hard',
    estimatedTime: '60 min',
    prerequisites: ['p1_num_sys'],
    progress: 0,
    completed: false,
    questionsSolved: 0,
    totalQuestions: 25,
    quizScore: 0,
    lastAttempt: null,
    description: 'Factorials, arrangements (nPr), selections (nCr), circular seating permutations, and word formation.',
    videoLinks: {
      tamil: 'http://www.youtube.com/playlist?list=PL1lPSVzW89HbDUfnF-h7uoeP73vsPeZyj',
      english: 'http://www.youtube.com/playlist?list=PLpyc33gOcbVA4qXMoQ5vmhefTruk5t9lt',
    },
    shortcuts: [
      'nPr = n! / (n - r)!, nCr = n! / [r! (n - r)!].',
      'Circular permutations of n items = (n - 1)!.',
      'Permutation with repetitions: n! / (p! × q!).',
    ],
  },
  {
    topicId: 'p3_probability',
    phase: 3,
    phaseTitle: 'Phase 3 – Advanced Arithmetic',
    category: 'Quantitative Aptitude',
    topicName: 'Probability',
    difficulty: 'Hard',
    estimatedTime: '55 min',
    prerequisites: ['p3_permutation_comb'],
    progress: 0,
    completed: false,
    questionsSolved: 0,
    totalQuestions: 25,
    quizScore: 0,
    lastAttempt: null,
    description: 'Sample space, dice rolling, card draws, independent events, mutually exclusive events, and Bayes theorem.',
    videoLinks: {
      tamil: 'http://www.youtube.com/playlist?list=PL1lPSVzW89HbDUfnF-h7uoeP73vsPeZyj',
      english: 'http://www.youtube.com/playlist?list=PLpyc33gOcbVA4qXMoQ5vmhefTruk5t9lt',
    },
    shortcuts: [
      'P(E) = Favorable Outcomes / Total Sample Space.',
      'P(A ∪ B) = P(A) + P(B) - P(A ∩ B).',
      'For independent events: P(A ∩ B) = P(A) × P(B).',
    ],
  },

  // ==========================================
  // PHASE 4: DATA INTERPRETATION (5 Topics)
  // ==========================================
  {
    topicId: 'p4_tables',
    phase: 4,
    phaseTitle: 'Phase 4 – Data Interpretation',
    category: 'Data Interpretation',
    topicName: 'Tables',
    difficulty: 'Medium',
    estimatedTime: '45 min',
    prerequisites: ['p1_percentages', 'p1_average'],
    progress: 0,
    completed: false,
    questionsSolved: 0,
    totalQuestions: 20,
    quizScore: 0,
    lastAttempt: null,
    description: 'Multi-column financial tables, missing data grids, company growth percentages, and ratio comparisons.',
    videoLinks: {
      tamil: 'http://www.youtube.com/playlist?list=PL1lPSVzW89HbDUfnF-h7uoeP73vsPeZyj',
      english: 'http://www.youtube.com/playlist?list=PLpyc33gOcbVBvdfzlSn97a1TlfysSPwm-',
    },
    shortcuts: [
      'Quick approximation by rounding denominators to nearest tens.',
      'Growth % = [(Final - Initial) / Initial] × 100.',
    ],
  },
  {
    topicId: 'p4_bar_graph',
    phase: 4,
    phaseTitle: 'Phase 4 – Data Interpretation',
    category: 'Data Interpretation',
    topicName: 'Bar Graph',
    difficulty: 'Easy',
    estimatedTime: '40 min',
    prerequisites: ['p1_percentages'],
    progress: 0,
    completed: false,
    questionsSolved: 0,
    totalQuestions: 20,
    quizScore: 0,
    lastAttempt: null,
    description: 'Single, grouped, and stacked bar charts for sales, export-import, and population trends.',
    videoLinks: {
      tamil: 'http://www.youtube.com/playlist?list=PL1lPSVzW89HbDUfnF-h7uoeP73vsPeZyj',
      english: 'http://www.youtube.com/playlist?list=PLpyc33gOcbVBvdfzlSn97a1TlfysSPwm-',
    },
    shortcuts: [
      'Compare heights directly before full numerical calculation.',
    ],
  },
  {
    topicId: 'p4_pie_chart',
    phase: 4,
    phaseTitle: 'Phase 4 – Data Interpretation',
    category: 'Data Interpretation',
    topicName: 'Pie Chart',
    difficulty: 'Medium',
    estimatedTime: '45 min',
    prerequisites: ['p1_percentages'],
    progress: 0,
    completed: false,
    questionsSolved: 0,
    totalQuestions: 25,
    quizScore: 0,
    lastAttempt: null,
    description: 'Single & dual pie charts, degree-to-percentage conversions (360° = 100%), and market share splits.',
    videoLinks: {
      tamil: 'http://www.youtube.com/playlist?list=PL1lPSVzW89HbDUfnF-h7uoeP73vsPeZyj',
      english: 'http://www.youtube.com/playlist?list=PLpyc33gOcbVBvdfzlSn97a1TlfysSPwm-',
    },
    shortcuts: [
      'Degree conversion: 1% = 3.6°. Angle = (% / 100) × 360°.',
    ],
  },
  {
    topicId: 'p4_line_graph',
    phase: 4,
    phaseTitle: 'Phase 4 – Data Interpretation',
    category: 'Data Interpretation',
    topicName: 'Line Graph',
    difficulty: 'Medium',
    estimatedTime: '45 min',
    prerequisites: ['p1_percentages'],
    progress: 0,
    completed: false,
    questionsSolved: 0,
    totalQuestions: 20,
    quizScore: 0,
    lastAttempt: null,
    description: 'Continuous time-series line graphs, profit vs expenditure analysis, and steepness slope comparisons.',
    videoLinks: {
      tamil: 'http://www.youtube.com/playlist?list=PL1lPSVzW89HbDUfnF-h7uoeP73vsPeZyj',
      english: 'http://www.youtube.com/playlist?list=PLpyc33gOcbVBvdfzlSn97a1TlfysSPwm-',
    },
    shortcuts: [
      'Slope indicates rate of growth (steepest rise = highest absolute or percentage increase).',
    ],
  },
  {
    topicId: 'p4_caselet_di',
    phase: 4,
    phaseTitle: 'Phase 4 – Data Interpretation',
    category: 'Data Interpretation',
    topicName: 'Caselet DI',
    difficulty: 'Hard',
    estimatedTime: '55 min',
    prerequisites: ['p4_tables'],
    progress: 0,
    completed: false,
    questionsSolved: 0,
    totalQuestions: 20,
    quizScore: 0,
    lastAttempt: null,
    description: 'Paragraph-based unstructured data passages, Venn diagram modeling, and multi-variable extraction.',
    videoLinks: {
      tamil: 'http://www.youtube.com/playlist?list=PL1lPSVzW89HbDUfnF-h7uoeP73vsPeZyj',
      english: 'http://www.youtube.com/playlist?list=PLpyc33gOcbVBvdfzlSn97a1TlfysSPwm-',
    },
    shortcuts: [
      'Draw a structured table or 3-set Venn diagram before reading question queries.',
    ],
  },

  // ==========================================
  // PHASE 5: LOGICAL REASONING (8 Topics)
  // ==========================================
  {
    topicId: 'p5_number_series',
    phase: 5,
    phaseTitle: 'Phase 5 – Logical Reasoning',
    category: 'Logical Reasoning',
    topicName: 'Number Series',
    difficulty: 'Easy',
    estimatedTime: '35 min',
    prerequisites: ['p1_num_sys'],
    progress: 0,
    completed: false,
    questionsSolved: 0,
    totalQuestions: 25,
    quizScore: 0,
    lastAttempt: null,
    description: 'Arithmetic progressions, geometric ratios, alternating differences, prime series, and square/cube patterns.',
    videoLinks: {
      tamil: 'http://www.youtube.com/playlist?list=PL1lPSVzW89HbDUfnF-h7uoeP73vsPeZyj',
      english: 'http://www.youtube.com/playlist?list=PLpyc33gOcbVADMKqylI__O_O_RMeHTyNK',
    },
    shortcuts: [
      'Take 1st and 2nd level differences if pattern is not obvious.',
      'Check (n² ± k) and (n³ ± k) sequences.',
    ],
  },
  {
    topicId: 'p5_letter_series',
    phase: 5,
    phaseTitle: 'Phase 5 – Logical Reasoning',
    category: 'Logical Reasoning',
    topicName: 'Letter Series',
    difficulty: 'Easy',
    estimatedTime: '35 min',
    prerequisites: [],
    progress: 0,
    completed: false,
    questionsSolved: 0,
    totalQuestions: 20,
    quizScore: 0,
    lastAttempt: null,
    description: 'Alphabetical position cycles, continuous repeating patterns, and missing cluster deductions.',
    videoLinks: {
      tamil: 'http://www.youtube.com/playlist?list=PL1lPSVzW89HbDUfnF-h7uoeP73vsPeZyj',
      english: 'http://www.youtube.com/playlist?list=PLpyc33gOcbVADMKqylI__O_O_RMeHTyNK',
    },
    shortcuts: [
      'Use EJOTY (5, 10, 15, 20, 25) for rapid letter-to-index mapping.',
    ],
  },
  {
    topicId: 'p5_coding_decoding',
    phase: 5,
    phaseTitle: 'Phase 5 – Logical Reasoning',
    category: 'Logical Reasoning',
    topicName: 'Coding-Decoding',
    difficulty: 'Medium',
    estimatedTime: '40 min',
    prerequisites: ['p5_letter_series'],
    progress: 0,
    completed: false,
    questionsSolved: 0,
    totalQuestions: 25,
    quizScore: 0,
    lastAttempt: null,
    description: 'Letter shift codes, reverse opposite letter pairs (sum=27), number substitutions, and fictitious language deciphering.',
    videoLinks: {
      tamil: 'http://www.youtube.com/playlist?list=PL1lPSVzW89HbDUfnF-h7uoeP73vsPeZyj',
      english: 'http://www.youtube.com/playlist?list=PLpyc33gOcbVADMKqylI__O_O_RMeHTyNK',
    },
    shortcuts: [
      'Opposite letter pairs: A-Z, B-Y, C-X, D-W, E-V, F-U, G-T, H-S, I-R, J-Q, K-P, L-O, M-N.',
    ],
  },
  {
    topicId: 'p5_blood_relations',
    phase: 5,
    phaseTitle: 'Phase 5 – Logical Reasoning',
    category: 'Logical Reasoning',
    topicName: 'Blood Relations',
    difficulty: 'Medium',
    estimatedTime: '45 min',
    prerequisites: [],
    progress: 0,
    completed: false,
    questionsSolved: 0,
    totalQuestions: 25,
    quizScore: 0,
    lastAttempt: null,
    description: 'Family tree hierarchies, coded relationship symbols (A+B, A-B), and portrait pointer puzzles.',
    videoLinks: {
      tamil: 'http://www.youtube.com/playlist?list=PL1lPSVzW89HbDUfnF-h7uoeP73vsPeZyj',
      english: 'http://www.youtube.com/playlist?list=PLpyc33gOcbVADMKqylI__O_O_RMeHTyNK',
    },
    shortcuts: [
      'Family Tree: (+) Male, (-) Female, (=) Married, (|) Parent-Child, (--) Siblings.',
    ],
  },
  {
    topicId: 'p5_direction_sense',
    phase: 5,
    phaseTitle: 'Phase 5 – Logical Reasoning',
    category: 'Logical Reasoning',
    topicName: 'Direction Sense',
    difficulty: 'Easy',
    estimatedTime: '35 min',
    prerequisites: [],
    progress: 0,
    completed: false,
    questionsSolved: 0,
    totalQuestions: 20,
    quizScore: 0,
    lastAttempt: null,
    description: '8 compass directions, turn angles (clockwise/anti-clockwise), Pythagoras shortest distance, and morning/evening shadow orientation.',
    videoLinks: {
      tamil: 'http://www.youtube.com/playlist?list=PL1lPSVzW89HbDUfnF-h7uoeP73vsPeZyj',
      english: 'http://www.youtube.com/playlist?list=PLpyc33gOcbVADMKqylI__O_O_RMeHTyNK',
    },
    shortcuts: [
      'Shortest displacement = √(Δx² + Δy²). Sunrise shadow falls West; sunset shadow falls East.',
    ],
  },
  {
    topicId: 'p5_syllogism',
    phase: 5,
    phaseTitle: 'Phase 5 – Logical Reasoning',
    category: 'Logical Reasoning',
    topicName: 'Syllogism',
    difficulty: 'Hard',
    estimatedTime: '50 min',
    prerequisites: [],
    progress: 0,
    completed: false,
    questionsSolved: 0,
    totalQuestions: 30,
    quizScore: 0,
    lastAttempt: null,
    description: 'Statement-conclusion logic, All/Some/No relationships, "Only a few" rules, and possibility Venn diagrams.',
    videoLinks: {
      tamil: 'http://www.youtube.com/playlist?list=PL1lPSVzW89HbDUfnF-h7uoeP73vsPeZyj',
      english: 'http://www.youtube.com/playlist?list=PLpyc33gOcbVADMKqylI__O_O_RMeHTyNK',
    },
    shortcuts: [
      'All A are B + All B are C => All A are C.',
      'Either-Or Condition: 1 positive + 1 negative conclusion, same subjects, both individually uncertain.',
    ],
  },
  {
    topicId: 'p5_seating_arrangement',
    phase: 5,
    phaseTitle: 'Phase 5 – Logical Reasoning',
    category: 'Logical Reasoning',
    topicName: 'Seating Arrangement',
    difficulty: 'Hard',
    estimatedTime: '60 min',
    prerequisites: ['p5_direction_sense'],
    progress: 0,
    completed: false,
    questionsSolved: 0,
    totalQuestions: 25,
    quizScore: 0,
    lastAttempt: null,
    description: 'Linear 1-row/2-row (facing North/South) and circular seating (facing inward/outward) placement puzzles.',
    videoLinks: {
      tamil: 'http://www.youtube.com/playlist?list=PL1lPSVzW89HbDUfnF-h7uoeP73vsPeZyj',
      english: 'http://www.youtube.com/playlist?list=PLpyc33gOcbVADMKqylI__O_O_RMeHTyNK',
    },
    shortcuts: [
      'Circular facing center: Left is clockwise, Right is anti-clockwise.',
      'Start with definite anchor position clues first.',
    ],
  },
  {
    topicId: 'p5_logical_puzzles',
    phase: 5,
    phaseTitle: 'Phase 5 – Logical Reasoning',
    category: 'Logical Reasoning',
    topicName: 'Logical Puzzles',
    difficulty: 'Hard',
    estimatedTime: '60 min',
    prerequisites: ['p5_seating_arrangement'],
    progress: 0,
    completed: false,
    questionsSolved: 0,
    totalQuestions: 25,
    quizScore: 0,
    lastAttempt: null,
    description: 'Floor-based puzzles, box stacking, scheduling calendars, and multi-attribute grid matching.',
    videoLinks: {
      tamil: 'http://www.youtube.com/playlist?list=PL1lPSVzW89HbDUfnF-h7uoeP73vsPeZyj',
      english: 'http://www.youtube.com/playlist?list=PLpyc33gOcbVADMKqylI__O_O_RMeHTyNK',
    },
    shortcuts: [
      'Construct a 2D matrix table (attributes on columns, entities on rows) to eliminate contradictions.',
    ],
  },

  // ==========================================
  // PHASE 6: VERBAL ABILITY (6 Topics)
  // ==========================================
  {
    topicId: 'p6_grammar',
    phase: 6,
    phaseTitle: 'Phase 6 – Verbal Ability',
    category: 'Verbal Ability',
    topicName: 'Grammar',
    difficulty: 'Medium',
    estimatedTime: '45 min',
    prerequisites: [],
    progress: 0,
    completed: false,
    questionsSolved: 0,
    totalQuestions: 30,
    quizScore: 0,
    lastAttempt: null,
    description: 'Parts of speech, tense consistency, subject-verb agreement, and modifier placement rules.',
    videoLinks: {
      tamil: 'http://www.youtube.com/playlist?list=PL1lPSVzW89HbDUfnF-h7uoeP73vsPeZyj',
      english: 'http://www.youtube.com/playlist?list=PLpyc33gOcbVBbD8Vfy-gCbivjSSHbMpUX',
    },
    shortcuts: [
      'Singular subjects take singular verbs: "The group of students is...".',
      '"Neither/Either of" always takes a singular verb.',
    ],
  },
  {
    topicId: 'p6_sentence_correction',
    phase: 6,
    phaseTitle: 'Phase 6 – Verbal Ability',
    category: 'Verbal Ability',
    topicName: 'Sentence Correction',
    difficulty: 'Medium',
    estimatedTime: '45 min',
    prerequisites: ['p6_grammar'],
    progress: 0,
    completed: false,
    questionsSolved: 0,
    totalQuestions: 25,
    quizScore: 0,
    lastAttempt: null,
    description: 'Error spotting in clauses, parallelism, idiom usage, preposition errors, and redundancy reduction.',
    videoLinks: {
      tamil: 'http://www.youtube.com/playlist?list=PL1lPSVzW89HbDUfnF-h7uoeP73vsPeZyj',
      english: 'http://www.youtube.com/playlist?list=PLpyc33gOcbVBbD8Vfy-gCbivjSSHbMpUX',
    },
    shortcuts: [
      'Maintain grammatical parallelism in lists: "singing, dancing, and acting".',
      'Watch for dangling modifiers at the start of participial phrases.',
    ],
  },
  {
    topicId: 'p6_vocabulary',
    phase: 6,
    phaseTitle: 'Phase 6 – Verbal Ability',
    category: 'Verbal Ability',
    topicName: 'Vocabulary',
    difficulty: 'Medium',
    estimatedTime: '40 min',
    prerequisites: [],
    progress: 0,
    completed: false,
    questionsSolved: 0,
    totalQuestions: 30,
    quizScore: 0,
    lastAttempt: null,
    description: 'High-frequency GRE/Placement words, root words, prefixes/suffixes, and contextual sentence fillers.',
    videoLinks: {
      tamil: 'http://www.youtube.com/playlist?list=PL1lPSVzW89HbDUfnF-h7uoeP73vsPeZyj',
      english: 'http://www.youtube.com/playlist?list=PLpyc33gOcbVBbD8Vfy-gCbivjSSHbMpUX',
    },
    shortcuts: [
      'Root word strategy: "Bene" = good (Benefactor, Benevolent), "Mal" = bad (Malicious).',
    ],
  },
  {
    topicId: 'p6_synonyms_antonyms',
    phase: 6,
    phaseTitle: 'Phase 6 – Verbal Ability',
    category: 'Verbal Ability',
    topicName: 'Synonyms & Antonyms',
    difficulty: 'Medium',
    estimatedTime: '40 min',
    prerequisites: ['p6_vocabulary'],
    progress: 0,
    completed: false,
    questionsSolved: 0,
    totalQuestions: 25,
    quizScore: 0,
    lastAttempt: null,
    description: 'Nuanced word relationships, tone matching (positive vs negative connotation), and context clues.',
    videoLinks: {
      tamil: 'http://www.youtube.com/playlist?list=PL1lPSVzW89HbDUfnF-h7uoeP73vsPeZyj',
      english: 'http://www.youtube.com/playlist?list=PLpyc33gOcbVBbD8Vfy-gCbivjSSHbMpUX',
    },
    shortcuts: [
      'Eliminate options that have identical meanings when looking for single antonyms.',
    ],
  },
  {
    topicId: 'p6_reading_comprehension',
    phase: 6,
    phaseTitle: 'Phase 6 – Verbal Ability',
    category: 'Verbal Ability',
    topicName: 'Reading Comprehension',
    difficulty: 'Hard',
    estimatedTime: '55 min',
    prerequisites: ['p6_vocabulary'],
    progress: 0,
    completed: false,
    questionsSolved: 0,
    totalQuestions: 20,
    quizScore: 0,
    lastAttempt: null,
    description: 'Passage skimming, central theme identification, tone analysis, inference extraction, and title selection.',
    videoLinks: {
      tamil: 'http://www.youtube.com/playlist?list=PL1lPSVzW89HbDUfnF-h7uoeP73vsPeZyj',
      english: 'http://www.youtube.com/playlist?list=PLpyc33gOcbVBbD8Vfy-gCbivjSSHbMpUX',
    },
    shortcuts: [
      'Read questions first to identify target keywords before diving into the passage text.',
    ],
  },
  {
    topicId: 'p6_para_jumbles',
    phase: 6,
    phaseTitle: 'Phase 6 – Verbal Ability',
    category: 'Verbal Ability',
    topicName: 'Para Jumbles',
    difficulty: 'Hard',
    estimatedTime: '50 min',
    prerequisites: ['p6_sentence_correction'],
    progress: 0,
    completed: false,
    questionsSolved: 0,
    totalQuestions: 20,
    quizScore: 0,
    lastAttempt: null,
    description: 'Sentence reordering, finding mandatory noun-pronoun pairs, chronology flow, and transition connectors.',
    videoLinks: {
      tamil: 'http://www.youtube.com/playlist?list=PL1lPSVzW89HbDUfnF-h7uoeP73vsPeZyj',
      english: 'http://www.youtube.com/playlist?list=PLpyc33gOcbVBbD8Vfy-gCbivjSSHbMpUX',
    },
    shortcuts: [
      'Rule out sentences starting with "However", "Therefore", "Furthermore" as opening sentences.',
    ],
  },
];
