// =========================================================================
// SGIP PLACEMENT ROADMAP - STAGE 2: LEETCODE & DSA ROADMAP (14 PHASES)
// =========================================================================

export const DSA_PHASES = [
  {
    id: 1,
    title: "Phase 1 – Programming & Problem-Solving Basics",
    desc: "Time Complexity, Space Complexity, Big-O, Input/Output, Basic Arrays & Strings, Loops, Conditions, and Math.",
    targetProblems: 15,
    icon: "Code2",
    color: "from-blue-600 to-cyan-500",
  },
  {
    id: 2,
    title: "Phase 2 – Arrays",
    desc: "Traversal, Min/Max, Prefix Sum, Frequency Counting, Kadane's Algorithm, Two Sum Pattern, Sorting + Arrays, Subarrays.",
    targetProblems: 25,
    icon: "LayoutGrid",
    color: "from-indigo-600 to-purple-500",
  },
  {
    id: 3,
    title: "Phase 3 – Strings",
    desc: "String Traversal, Character Frequency, Anagrams, Palindromes, Manipulation, Substrings, Two Pointer on Strings.",
    targetProblems: 20,
    icon: "Type",
    color: "from-emerald-600 to-teal-500",
  },
  {
    id: 4,
    title: "Phase 4 – HashMap & HashSet",
    desc: "Frequency Map, Duplicate Detection, Lookup Optimization, Two Sum, Group Anagrams, Longest Consecutive Sequence.",
    targetProblems: 20,
    icon: "Database",
    color: "from-amber-600 to-orange-500",
  },
  {
    id: 5,
    title: "Phase 5 – Two Pointers",
    desc: "Opposite Direction, Same Direction, Pair Sum, Remove Duplicates, Palindrome Verification, Container Problems.",
    targetProblems: 15,
    icon: "MoveHorizontal",
    color: "from-rose-600 to-pink-500",
  },
  {
    id: 6,
    title: "Phase 6 – Sliding Window",
    desc: "Fixed Window, Variable Window, Longest Substring, Maximum Sum Subarray, Frequency Window, At Most K.",
    targetProblems: 20,
    icon: "Maximize2",
    color: "from-violet-600 to-purple-500",
  },
  {
    id: 7,
    title: "Phase 7 – Stack & Queue",
    desc: "Stack Basics, Valid Parentheses, Min Stack, Monotonic Stack, Queue, Deque, Next Greater Element.",
    targetProblems: 20,
    icon: "Layers",
    color: "from-blue-600 to-indigo-500",
  },
  {
    id: 8,
    title: "Phase 8 – Linked List",
    desc: "Traversal, Insert/Delete, Reverse Linked List, Fast & Slow Pointers, Detect Cycle, Merge Lists, Remove Nth Node, Reordering.",
    targetProblems: 20,
    icon: "GitCommit",
    color: "from-emerald-600 to-green-500",
  },
  {
    id: 9,
    title: "Phase 9 – Binary Search",
    desc: "Basic Binary Search, Search Insert Position, First/Last Position, Rotated Sorted Array, BS on Answer, Search 2D Matrix.",
    targetProblems: 20,
    icon: "Search",
    color: "from-cyan-600 to-blue-500",
  },
  {
    id: 10,
    title: "Phase 10 – Recursion & Backtracking",
    desc: "Recursion Tree, Subsets, Permutations, Combination Sum, Generate Parentheses, N-Queens, Backtracking Pattern.",
    targetProblems: 20,
    icon: "RotateCw",
    color: "from-amber-600 to-yellow-500",
  },
  {
    id: 11,
    title: "Phase 11 – Trees",
    desc: "Binary Tree Traversal, DFS, BFS, Level Order, Max Depth, Diameter, LCA, Binary Search Tree (BST).",
    targetProblems: 25,
    icon: "Network",
    color: "from-green-600 to-emerald-500",
  },
  {
    id: 12,
    title: "Phase 12 – Heap / Priority Queue",
    desc: "Min Heap, Max Heap, Kth Largest Element, Top K Frequent Elements, Merge K Sorted Lists, PQ Applications.",
    targetProblems: 15,
    icon: "ListOrdered",
    color: "from-purple-600 to-pink-500",
  },
  {
    id: 13,
    title: "Phase 13 – Graphs",
    desc: "Graph Representation, BFS, DFS, Connected Components, Number of Islands, Cycle Detection, Topological Sort, Shortest Path, Union Find.",
    targetProblems: 25,
    icon: "Share2",
    color: "from-rose-600 to-red-500",
  },
  {
    id: 14,
    title: "Phase 14 – Dynamic Programming",
    desc: "DP Intro, Memoization, Tabulation, 1D DP, 2D DP, Climbing Stairs, House Robber, Coin Change, LCS, 0/1 Knapsack.",
    targetProblems: 25,
    icon: "Sparkles",
    color: "from-yellow-500 to-amber-600",
  },
];

export const PATTERN_RECOGNITION_GUIDE = [
  {
    id: "two_pointers",
    name: "Two Pointers Pattern",
    whenToUse: "When searching for pairs in a sorted array, palindrome verification, or in-place array reordering.",
    clues: ["Array is sorted", "Find pair with sum X", "Compare characters from both ends", "Reverse in-place"],
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    classicProblems: ["Two Sum II (Sorted)", "Valid Palindrome", "Container With Most Water", "3Sum"],
  },
  {
    id: "sliding_window",
    name: "Sliding Window Pattern",
    whenToUse: "When dealing with continuous subarrays or substrings where you need to find min/max length with a constraint.",
    clues: ["Continuous subarray / substring", "Find longest/shortest window", "Max sum of size K", "At most K distinct elements"],
    timeComplexity: "O(n)",
    spaceComplexity: "O(k) or O(1)",
    classicProblems: ["Max Sum Subarray of Size K", "Longest Substring Without Repeating Characters", "Minimum Window Substring"],
  },
  {
    id: "hash_map",
    name: "HashMap & Frequency Counting",
    whenToUse: "When you need O(1) instant lookups, frequency count tracking, or finding duplicates.",
    clues: ["Count frequencies", "O(1) search needed", "Find duplicates", "Two Sum unsorted"],
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    classicProblems: ["Two Sum", "Valid Anagram", "Group Anagrams", "Top K Frequent Elements"],
  },
  {
    id: "binary_search",
    name: "Binary Search / Search on Answer",
    whenToUse: "When the search space is monotonically sorted, or when minimizing the maximum capacity/allocation.",
    clues: ["Sorted array", "O(log n) requirement", "Find minimum capacity to ship in D days", "Koko Eating Bananas"],
    timeComplexity: "O(log n)",
    spaceComplexity: "O(1)",
    classicProblems: ["Binary Search", "Search in Rotated Sorted Array", "Find Minimum in Rotated Sorted Array", "Koko Eating Bananas"],
  },
  {
    id: "monotonic_stack",
    name: "Monotonic Stack Pattern",
    whenToUse: "When looking for the Next Greater Element, Next Smaller Element, or computing histogram areas.",
    clues: ["Next greater/smaller element", "Histogram area", "Daily temperatures", "Online stock span"],
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    classicProblems: ["Next Greater Element", "Daily Temperatures", "Largest Rectangle in Histogram"],
  },
  {
    id: "fast_slow_pointers",
    name: "Fast & Slow Pointers (Floyd's Cycle)",
    whenToUse: "When detecting cycles in a Linked List or finding the middle element in a single pass.",
    clues: ["Linked List cycle", "Find middle of linked list", "Find duplicate number in 1..n"],
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    classicProblems: ["Linked List Cycle", "Middle of Linked List", "Happy Number"],
  },
  {
    id: "bfs_dfs_trees_graphs",
    name: "BFS (Queue) vs DFS (Recursion/Stack)",
    whenToUse: "Use BFS for shortest path in unweighted graphs or level-order tree traversal. Use DFS for deep path searching, topological sort, and island counting.",
    clues: ["Shortest path in matrix", "Level order traversal", "Number of connected islands", "Word Ladder"],
    timeComplexity: "O(V + E)",
    spaceComplexity: "O(V)",
    classicProblems: ["Binary Tree Level Order", "Number of Islands", "Course Schedule", "Clone Graph"],
  },
  {
    id: "dynamic_programming",
    name: "Dynamic Programming (Optimal Substructure)",
    whenToUse: "When a problem has overlapping subproblems and optimal substructure (choices like take/don't take).",
    clues: ["Count total ways", "Find min/max cost", "Choice of taking or skipping element", "Fibonacci / 0-1 Knapsack"],
    timeComplexity: "O(n) to O(n × target)",
    spaceComplexity: "O(n) or O(1) space optimized",
    classicProblems: ["Climbing Stairs", "House Robber", "Coin Change", "Longest Common Subsequence"],
  },
];

export const getLeetCodeUrl = (prob) => {
  if (prob.leetcodeUrl) return prob.leetcodeUrl;
  const slug = prob.title
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-');
  return `https://leetcode.com/problems/${slug}/`;
};

export const INITIAL_DSA_PROBLEMS = [
  // Phase 1: Basics
  {
    problemId: "p1_1",
    leetcodeNumber: 1929,
    title: "Concatenation of Array",
    leetcodeUrl: "https://leetcode.com/problems/concatenation-of-array/",
    phase: 1,
    phaseTitle: "Phase 1 – Basics",
    difficulty: "Easy",
    patterns: ["Array Traversal"],
    topics: ["Arrays", "Basics"],
    companyTags: ["TCS", "Infosys", "Capgemini"],
    acceptanceRate: "89.8%",
    estimatedTime: "15 min",
    status: "Solved",
    attempts: 1,
    bestRuntime: "1 ms",
    bestMemory: "44.2 MB",
    notes: "Allocated new array of size 2*n and copied nums[i] to ans[i] and ans[i+n].",
    description: "Given an integer array nums of length n, return an array ans of length 2n where ans[i] == nums[i] and ans[i + n] == nums[i].",
    approach: "Create array of size 2n. Loop from 0 to n-1: ans[i] = nums[i] and ans[i+n] = nums[i].",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
  },
  {
    problemId: "p1_2",
    leetcodeNumber: 9,
    title: "Palindrome Number",
    leetcodeUrl: "https://leetcode.com/problems/palindrome-number/",
    phase: 1,
    phaseTitle: "Phase 1 – Basics",
    difficulty: "Easy",
    patterns: ["Math", "Two Pointers"],
    topics: ["Math", "Basics"],
    companyTags: ["Amazon", "TCS", "Wipro"],
    acceptanceRate: "56.2%",
    estimatedTime: "15 min",
    status: "Solved",
    attempts: 2,
    bestRuntime: "4 ms",
    bestMemory: "43.1 MB",
    notes: "Negative numbers are never palindromes. Reversing half of number avoids overflow.",
    description: "Given an integer x, return true if x is a palindrome, and false otherwise without converting to a string.",
    approach: "If x < 0 or (x % 10 == 0 && x != 0) return false. Reverse second half: rev = rev * 10 + x % 10; x /= 10. Check if x == rev or x == rev/10.",
    timeComplexity: "O(log10 n)",
    spaceComplexity: "O(1)",
  },

  // Phase 2: Arrays
  {
    problemId: "p2_1",
    leetcodeNumber: 1,
    title: "Two Sum",
    leetcodeUrl: "https://leetcode.com/problems/two-sum/",
    phase: 2,
    phaseTitle: "Phase 2 – Arrays",
    difficulty: "Easy",
    patterns: ["HashMap", "Two Sum Pattern"],
    topics: ["Arrays", "HashMap"],
    companyTags: ["Amazon", "Microsoft", "Google", "TCS", "Infosys"],
    acceptanceRate: "52.4%",
    estimatedTime: "20 min",
    status: "Solved",
    attempts: 2,
    bestRuntime: "2 ms",
    bestMemory: "44.8 MB",
    notes: "Used HashMap for complement lookup in single pass. Key: nums[i], Value: index.",
    description: "Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.",
    approach: "Iterate with HashMap. For each num, complement = target - num. If map contains complement, return [map.get(complement), i]. Else put (num, i).",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
  },
  {
    problemId: "p2_2",
    leetcodeNumber: 53,
    title: "Maximum Subarray (Kadane's Algorithm)",
    phase: 2,
    phaseTitle: "Phase 2 – Arrays",
    difficulty: "Medium",
    patterns: ["Kadane's Algorithm", "Dynamic Programming"],
    topics: ["Arrays", "Dynamic Programming"],
    companyTags: ["Amazon", "Microsoft", "TCS", "Cognizant"],
    acceptanceRate: "51.1%",
    estimatedTime: "25 min",
    status: "Solved",
    attempts: 1,
    bestRuntime: "1 ms",
    bestMemory: "51.3 MB",
    notes: "Kadane's algorithm: currSum = Math.max(nums[i], currSum + nums[i]). Reset if sum drops below element.",
    description: "Given an integer array nums, find the subarray with the largest sum, and return its sum.",
    approach: "Maintain currSum and maxSum. For each num, currSum = max(num, currSum + num), maxSum = max(maxSum, currSum).",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
  },
  {
    problemId: "p2_3",
    leetcodeNumber: 121,
    title: "Best Time to Buy and Sell Stock",
    phase: 2,
    phaseTitle: "Phase 2 – Arrays",
    difficulty: "Easy",
    patterns: ["Two Pointers", "Prefix Min"],
    topics: ["Arrays", "Dynamic Programming"],
    companyTags: ["Amazon", "Infosys", "Wipro", "Accenture"],
    acceptanceRate: "54.7%",
    estimatedTime: "20 min",
    status: "Solved",
    attempts: 1,
    bestRuntime: "1 ms",
    bestMemory: "58.4 MB",
    notes: "Track minPrice seen so far and maxProfit = max(maxProfit, price - minPrice).",
    description: "You want to maximize your profit by choosing a single day to buy one stock and choosing a different day in the future to sell that stock.",
    approach: "Single pass: minPrice = min(minPrice, price), maxProfit = max(maxProfit, price - minPrice).",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
  },

  // Phase 3: Strings
  {
    problemId: "p3_1",
    leetcodeNumber: 242,
    title: "Valid Anagram",
    phase: 3,
    phaseTitle: "Phase 3 – Strings",
    difficulty: "Easy",
    patterns: ["Frequency Map", "Array as Map"],
    topics: ["Strings", "HashMap"],
    companyTags: ["Amazon", "Google", "TCS", "Accenture"],
    acceptanceRate: "64.1%",
    estimatedTime: "15 min",
    status: "Solved",
    attempts: 1,
    bestRuntime: "2 ms",
    bestMemory: "42.5 MB",
    notes: "Fixed size 26 integer array is faster than HashMap for lowercase English letters.",
    description: "Given two strings s and t, return true if t is an anagram of s, and false otherwise.",
    approach: "If lengths differ return false. Count frequency in int[26]: ++ for s, -- for t. Check if all zeros.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1) (26 chars)",
  },
  {
    problemId: "p3_2",
    leetcodeNumber: 125,
    title: "Valid Palindrome",
    phase: 3,
    phaseTitle: "Phase 3 – Strings",
    difficulty: "Easy",
    patterns: ["Two Pointers"],
    topics: ["Strings", "Two Pointers"],
    companyTags: ["Microsoft", "Capgemini", "Infosys"],
    acceptanceRate: "47.2%",
    estimatedTime: "15 min",
    status: "Solved",
    attempts: 1,
    bestRuntime: "3 ms",
    bestMemory: "42.8 MB",
    notes: "Used left and right pointers while skipping non-alphanumeric characters with Character.isLetterOrDigit.",
    description: "A phrase is a palindrome if, after converting all uppercase letters into lowercase letters and removing all non-alphanumeric characters, it reads the same forward and backward.",
    approach: "Two pointers left=0, right=len-1. Skip invalid characters. If lowercase chars mismatch return false.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
  },

  // Phase 4: HashMap
  {
    problemId: "p4_1",
    leetcodeNumber: 49,
    title: "Group Anagrams",
    phase: 4,
    phaseTitle: "Phase 4 – HashMap",
    difficulty: "Medium",
    patterns: ["HashMap", "String Sorting"],
    topics: ["HashMap", "Strings"],
    companyTags: ["Amazon", "Google", "Microsoft"],
    acceptanceRate: "68.3%",
    estimatedTime: "25 min",
    status: "In Progress",
    attempts: 2,
    bestRuntime: "6 ms",
    bestMemory: "47.2 MB",
    notes: "Sort each string as canonical key or use char frequency tuple as map key.",
    description: "Given an array of strings strs, group the anagrams together. You can return the answer in any order.",
    approach: "Map<String, List<String>>. Sort characters of each word to form key. Add original word to map list.",
    timeComplexity: "O(n × k log k)",
    spaceComplexity: "O(n × k)",
  },
  {
    problemId: "p4_2",
    leetcodeNumber: 128,
    title: "Longest Consecutive Sequence",
    phase: 4,
    phaseTitle: "Phase 4 – HashMap",
    difficulty: "Medium",
    patterns: ["HashSet", "Lookup Optimization"],
    topics: ["HashSet", "Arrays"],
    companyTags: ["Google", "Amazon", "TCS"],
    acceptanceRate: "48.2%",
    estimatedTime: "30 min",
    status: "In Progress",
    attempts: 1,
    bestRuntime: "14 ms",
    bestMemory: "65.8 MB",
    notes: "Only start counting sequence when (num - 1) is NOT in HashSet to ensure O(n) runtime.",
    description: "Given an unsorted array of integers nums, return the length of the longest consecutive elements sequence in O(n) time.",
    approach: "Insert all numbers into HashSet. For each num, if (!set.contains(num - 1)), count streak (num + 1, num + 2...).",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
  },

  // Phase 5: Two Pointers
  {
    problemId: "p5_1",
    leetcodeNumber: 11,
    title: "Container With Most Water",
    phase: 5,
    phaseTitle: "Phase 5 – Two Pointers",
    difficulty: "Medium",
    patterns: ["Two Pointers", "Greedy"],
    topics: ["Two Pointers", "Arrays"],
    companyTags: ["Amazon", "Google", "Microsoft", "Capgemini"],
    acceptanceRate: "55.1%",
    estimatedTime: "25 min",
    status: "Solved",
    attempts: 1,
    bestRuntime: "4 ms",
    bestMemory: "57.1 MB",
    notes: "Pointers at both ends. Always advance pointer with smaller height to search for larger area.",
    description: "Find two lines that together with the x-axis form a container, such that the container contains the most water.",
    approach: "left=0, right=n-1. area = min(height[left], height[right]) * (right - left). If height[left] < height[right] left++ else right--.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
  },
  {
    problemId: "p5_2",
    leetcodeNumber: 15,
    title: "3Sum",
    phase: 5,
    phaseTitle: "Phase 5 – Two Pointers",
    difficulty: "Medium",
    patterns: ["Two Pointers", "Sorting"],
    topics: ["Two Pointers", "Arrays"],
    companyTags: ["Amazon", "Microsoft", "Facebook"],
    acceptanceRate: "34.5%",
    estimatedTime: "30 min",
    status: "In Progress",
    attempts: 3,
    bestRuntime: "24 ms",
    bestMemory: "51.2 MB",
    notes: "Sort first. Fix index i, then run Two Pointers (left, right) for target -nums[i]. Skip duplicates carefully.",
    description: "Given an integer array nums, return all the triplets [nums[i], nums[j], nums[k]] such that i != j, i != k, and j != k, and nums[i] + nums[j] + nums[k] == 0 without duplicate triplets.",
    approach: "Sort array. Loop i from 0 to n-3. If nums[i] > 0 break. Run two pointers: left=i+1, right=n-1. Skip adjacent duplicates.",
    timeComplexity: "O(n²)",
    spaceComplexity: "O(1) (excluding output)",
  },

  // Phase 6: Sliding Window
  {
    problemId: "p6_1",
    leetcodeNumber: 3,
    title: "Longest Substring Without Repeating Characters",
    phase: 6,
    phaseTitle: "Phase 6 – Sliding Window",
    difficulty: "Medium",
    patterns: ["Sliding Window", "HashSet"],
    topics: ["Sliding Window", "Strings"],
    companyTags: ["Amazon", "Microsoft", "Google", "Infosys"],
    acceptanceRate: "35.1%",
    estimatedTime: "25 min",
    status: "Solved",
    attempts: 2,
    bestRuntime: "5 ms",
    bestMemory: "44.1 MB",
    notes: "Moving window with Set or int[128] index array. Shrink left pointer when duplicate detected.",
    description: "Given a string s, find the length of the longest substring without duplicate characters.",
    approach: "Sliding window [left, right]. Store last seen index in array. When char repeat occurs, left = max(left, lastSeen[c] + 1).",
    timeComplexity: "O(n)",
    spaceComplexity: "O(min(n, m))",
  },
  {
    problemId: "p6_2",
    leetcodeNumber: 424,
    title: "Longest Repeating Character Replacement",
    phase: 6,
    phaseTitle: "Phase 6 – Sliding Window",
    difficulty: "Medium",
    patterns: ["Sliding Window", "Frequency Window"],
    topics: ["Sliding Window", "Strings"],
    companyTags: ["Amazon", "Google"],
    acceptanceRate: "54.3%",
    estimatedTime: "30 min",
    status: "Unsolved",
    attempts: 0,
    bestRuntime: null,
    bestMemory: null,
    notes: "",
    description: "You are given a string s and an integer k. Choose any character and change it to any other uppercase English character at most k times. Return the length of the longest substring containing the same letter.",
    approach: "Window length - maxFrequencyInWindow <= k. If invalid, shrink left pointer by 1.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
  },

  // Phase 7: Stack & Queue
  {
    problemId: "p7_1",
    leetcodeNumber: 20,
    title: "Valid Parentheses",
    phase: 7,
    phaseTitle: "Phase 7 – Stack & Queue",
    difficulty: "Easy",
    patterns: ["Stack"],
    topics: ["Stack", "Strings"],
    companyTags: ["Amazon", "Microsoft", "TCS", "Accenture"],
    acceptanceRate: "41.2%",
    estimatedTime: "15 min",
    status: "Solved",
    attempts: 1,
    bestRuntime: "1 ms",
    bestMemory: "41.6 MB",
    notes: "Push closing parentheses or pop matching top. Check stack.isEmpty() at end.",
    description: "Given a string s containing just the characters '(', ')', '{', '}', '[' and ']', determine if the input string is valid.",
    approach: "Use Stack<Character>. Push expected closing bracket. If stack is empty or pop() != char, return false.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
  },
  {
    problemId: "p7_2",
    leetcodeNumber: 739,
    title: "Daily Temperatures",
    phase: 7,
    phaseTitle: "Phase 7 – Stack & Queue",
    difficulty: "Medium",
    patterns: ["Monotonic Stack"],
    topics: ["Stack", "Arrays"],
    companyTags: ["Amazon", "Google", "Microsoft"],
    acceptanceRate: "66.5%",
    estimatedTime: "25 min",
    status: "In Progress",
    attempts: 1,
    bestRuntime: "21 ms",
    bestMemory: "56.4 MB",
    notes: "Store indices in monotonic decreasing stack. Pop indices when current temp is higher.",
    description: "Given an array of integers temperatures, return an array answer such that answer[i] is the number of days you have to wait after the ith day to get a warmer temperature.",
    approach: "Monotonic decreasing stack of indices. When temperatures[i] > temperatures[stack.peek()], pop prevIndex and set ans[prevIndex] = i - prevIndex.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
  },

  // Phase 8: Linked List
  {
    problemId: "p8_1",
    leetcodeNumber: 206,
    title: "Reverse Linked List",
    phase: 8,
    phaseTitle: "Phase 8 – Linked List",
    difficulty: "Easy",
    patterns: ["Two Pointers", "In-place Reversal"],
    topics: ["Linked List"],
    companyTags: ["Amazon", "Microsoft", "TCS", "Infosys"],
    acceptanceRate: "76.4%",
    estimatedTime: "15 min",
    status: "Solved",
    attempts: 1,
    bestRuntime: "0 ms",
    bestMemory: "42.1 MB",
    notes: "Three pointers: prev = null, curr = head, nextNode = curr.next.",
    description: "Given the head of a singly linked list, reverse the list, and return the reversed list.",
    approach: "Iterative: while (curr != null) { next = curr.next; curr.next = prev; prev = curr; curr = next; } return prev.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
  },
  {
    problemId: "p8_2",
    leetcodeNumber: 141,
    title: "Linked List Cycle",
    phase: 8,
    phaseTitle: "Phase 8 – Linked List",
    difficulty: "Easy",
    patterns: ["Fast & Slow Pointers"],
    topics: ["Linked List", "Two Pointers"],
    companyTags: ["Amazon", "Microsoft", "Capgemini"],
    acceptanceRate: "50.1%",
    estimatedTime: "15 min",
    status: "Solved",
    attempts: 1,
    bestRuntime: "0 ms",
    bestMemory: "44.3 MB",
    notes: "Floyd's Cycle: slow advances 1 step, fast advances 2 steps. If slow == fast, cycle exists.",
    description: "Given head, the head of a linked list, determine if the linked list has a cycle in it.",
    approach: "slow = head, fast = head. while (fast != null && fast.next != null) { slow = slow.next; fast = fast.next.next; if (slow == fast) return true; } return false.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
  },

  // Phase 9: Binary Search
  {
    problemId: "p9_1",
    leetcodeNumber: 704,
    title: "Binary Search",
    phase: 9,
    phaseTitle: "Phase 9 – Binary Search",
    difficulty: "Easy",
    patterns: ["Binary Search"],
    topics: ["Binary Search", "Arrays"],
    companyTags: ["Amazon", "TCS", "Wipro", "Infosys"],
    acceptanceRate: "58.1%",
    estimatedTime: "10 min",
    status: "Solved",
    attempts: 1,
    bestRuntime: "0 ms",
    bestMemory: "45.2 MB",
    notes: "mid = left + (right - left) / 2 avoids integer overflow.",
    description: "Given an array of integers nums sorted in ascending order, and an integer target, write a function to search target in nums in O(log n).",
    approach: "low=0, high=n-1. mid = low + (high-low)/2. If nums[mid]==target return mid, if < target low=mid+1 else high=mid-1.",
    timeComplexity: "O(log n)",
    spaceComplexity: "O(1)",
  },
  {
    problemId: "p9_2",
    leetcodeNumber: 33,
    title: "Search in Rotated Sorted Array",
    phase: 9,
    phaseTitle: "Phase 9 – Binary Search",
    difficulty: "Medium",
    patterns: ["Binary Search"],
    topics: ["Binary Search", "Arrays"],
    companyTags: ["Amazon", "Microsoft", "Google"],
    acceptanceRate: "40.8%",
    estimatedTime: "30 min",
    status: "Unsolved",
    attempts: 1,
    bestRuntime: null,
    bestMemory: null,
    notes: "One half of rotated array is always normally sorted. Check if target lies within sorted half.",
    description: "Given the array nums after possible rotation and an integer target, return the index of target if it is in nums, or -1 if it is not.",
    approach: "If nums[low] <= nums[mid], left half is sorted. If target between nums[low] and nums[mid], high = mid - 1, else low = mid + 1. Otherwise right half is sorted.",
    timeComplexity: "O(log n)",
    spaceComplexity: "O(1)",
  },

  // Phase 10: Recursion & Backtracking
  {
    problemId: "p10_1",
    leetcodeNumber: 78,
    title: "Subsets",
    phase: 10,
    phaseTitle: "Phase 10 – Backtracking",
    difficulty: "Medium",
    patterns: ["Backtracking", "Pick / Don't Pick"],
    topics: ["Backtracking", "Recursion"],
    companyTags: ["Amazon", "Google", "Microsoft"],
    acceptanceRate: "78.4%",
    estimatedTime: "25 min",
    status: "In Progress",
    attempts: 1,
    bestRuntime: "1 ms",
    bestMemory: "42.6 MB",
    notes: "Standard backtracking template: add to current, backtrack(i+1), remove last element.",
    description: "Given an integer array nums of unique elements, return all possible subsets (the power set).",
    approach: "Backtracking: backtrack(start, currentList). Add copy of currentList to result. Loop i from start to n-1: add, recurse(i+1), remove.",
    timeComplexity: "O(n × 2^n)",
    spaceComplexity: "O(n)",
  },

  // Phase 11: Trees
  {
    problemId: "p11_1",
    leetcodeNumber: 104,
    title: "Maximum Depth of Binary Tree",
    phase: 11,
    phaseTitle: "Phase 11 – Trees",
    difficulty: "Easy",
    patterns: ["DFS", "Recursion Tree"],
    topics: ["Trees", "DFS"],
    companyTags: ["Amazon", "Google", "Infosys", "TCS"],
    acceptanceRate: "75.2%",
    estimatedTime: "15 min",
    status: "Solved",
    attempts: 1,
    bestRuntime: "0 ms",
    bestMemory: "42.9 MB",
    notes: "1 + Math.max(maxDepth(root.left), maxDepth(root.right)).",
    description: "Given the root of a binary tree, return its maximum depth.",
    approach: "Base case: if (root == null) return 0. Return 1 + Math.max(maxDepth(root.left), maxDepth(root.right)).",
    timeComplexity: "O(n)",
    spaceComplexity: "O(height)",
  },
  {
    problemId: "p11_2",
    leetcodeNumber: 102,
    title: "Binary Tree Level Order Traversal",
    phase: 11,
    phaseTitle: "Phase 11 – Trees",
    difficulty: "Medium",
    patterns: ["BFS", "Queue"],
    topics: ["Trees", "BFS"],
    companyTags: ["Amazon", "Microsoft", "Google"],
    acceptanceRate: "67.8%",
    estimatedTime: "25 min",
    status: "In Progress",
    attempts: 1,
    bestRuntime: "1 ms",
    bestMemory: "44.8 MB",
    notes: "Process level by level using Queue. Measure size = queue.size() at start of each level loop.",
    description: "Given the root of a binary tree, return the level order traversal of its nodes' values (i.e., from left to right, level by level).",
    approach: "Queue<TreeNode>. Loop while !q.isEmpty(): int levelSize = q.size(). For 0..levelSize: poll, add val to list, push left and right children.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
  },

  // Phase 12: Heap / Priority Queue
  {
    problemId: "p12_1",
    leetcodeNumber: 215,
    title: "Kth Largest Element in an Array",
    phase: 12,
    phaseTitle: "Phase 12 – Heap",
    difficulty: "Medium",
    patterns: ["Min Heap", "Top K Elements"],
    topics: ["Heap", "Priority Queue"],
    companyTags: ["Amazon", "Facebook", "Microsoft"],
    acceptanceRate: "67.2%",
    estimatedTime: "20 min",
    status: "In Progress",
    attempts: 1,
    bestRuntime: "5 ms",
    bestMemory: "54.1 MB",
    notes: "Min Heap of size k maintains the k largest elements. Peek is kth largest.",
    description: "Given an integer array nums and an integer k, return the kth largest element in the array.",
    approach: "PriorityQueue<Integer> minHeap. Add num; if (minHeap.size() > k) minHeap.poll(). Return minHeap.peek().",
    timeComplexity: "O(n log k)",
    spaceComplexity: "O(k)",
  },

  // Phase 13: Graphs
  {
    problemId: "p13_1",
    leetcodeNumber: 200,
    title: "Number of Islands",
    phase: 13,
    phaseTitle: "Phase 13 – Graphs",
    difficulty: "Medium",
    patterns: ["DFS", "BFS", "Grid Traversal"],
    topics: ["Graphs", "BFS", "DFS"],
    companyTags: ["Amazon", "Microsoft", "Google", "Capgemini"],
    acceptanceRate: "59.2%",
    estimatedTime: "30 min",
    status: "In Progress",
    attempts: 2,
    bestRuntime: "3 ms",
    bestMemory: "49.1 MB",
    notes: "Sink island during DFS: mark grid[r][c] = '0' to avoid re-visiting without extra visited array.",
    description: "Given an m x n 2D binary grid grid which represents a map of '1's (land) and '0's (water), return the number of islands.",
    approach: "Loop over every cell (r, c). When grid[r][c] == '1', islands++, dfs(r, c) to convert all 4-directional connected '1's to '0's.",
    timeComplexity: "O(m × n)",
    spaceComplexity: "O(m × n) recursive call stack",
  },

  // Phase 14: Dynamic Programming
  {
    problemId: "p14_1",
    leetcodeNumber: 70,
    title: "Climbing Stairs",
    phase: 14,
    phaseTitle: "Phase 14 – Dynamic Programming",
    difficulty: "Easy",
    patterns: ["1D DP", "Fibonacci"],
    topics: ["Dynamic Programming"],
    companyTags: ["Amazon", "TCS", "Infosys", "Wipro"],
    acceptanceRate: "53.2%",
    estimatedTime: "15 min",
    status: "Solved",
    attempts: 1,
    bestRuntime: "0 ms",
    bestMemory: "39.8 MB",
    notes: "dp[i] = dp[i-1] + dp[i-2]. Optimized to two variables for O(1) space.",
    description: "You are climbing a staircase. It takes n steps to reach the top. Each time you can either climb 1 or 2 steps. In how many distinct ways can you climb to the top?",
    approach: "prev2 = 1, prev1 = 2. Loop from 3 to n: curr = prev1 + prev2; prev2 = prev1; prev1 = curr. Return prev1.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
  },
  {
    problemId: "p14_2",
    leetcodeNumber: 198,
    title: "House Robber",
    phase: 14,
    phaseTitle: "Phase 14 – Dynamic Programming",
    difficulty: "Medium",
    patterns: ["1D DP", "Pick / Skip Choice"],
    topics: ["Dynamic Programming"],
    companyTags: ["Amazon", "Google", "Microsoft"],
    acceptanceRate: "51.1%",
    estimatedTime: "25 min",
    status: "Unsolved",
    attempts: 0,
    bestRuntime: null,
    bestMemory: null,
    notes: "",
    description: "You are planning to rob houses along a street. Each house has a certain amount of money stashed. Adjacent houses have security systems. Determine max money you can rob without alerting police.",
    approach: "rob = max(prevRob + nums[i], prevNotRob). Maintain two variables for O(1) space.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
  },
];

export const INITIAL_MISTAKE_JOURNAL = [
  {
    id: "mj_1",
    problemTitle: "Longest Substring Without Repeating Characters (#3)",
    mistake: "Initially tried nested O(n²) loops to generate all substrings instead of sliding window.",
    correctPattern: "Sliding Window + Last Seen Index Array",
    timeComplexity: "O(n)",
    spaceComplexity: "O(128) = O(1)",
    keyLearning: "Whenever dealing with continuous substring constraints, use a left-right sliding window and advance left pointer to lastSeen[char] + 1.",
    dateLogged: "2026-08-25",
  },
  {
    id: "mj_2",
    problemTitle: "Search in Rotated Sorted Array (#33)",
    mistake: "Forgot that one half is always strictly sorted. Tried standard binary search without identifying which half is sorted first.",
    correctPattern: "Modified Binary Search with Sorted Half Inspection",
    timeComplexity: "O(log n)",
    spaceComplexity: "O(1)",
    keyLearning: "Check nums[low] <= nums[mid] to determine if left half is sorted, then check if target falls inside that range.",
    dateLogged: "2026-08-26",
  },
  {
    id: "mj_3",
    problemTitle: "Valid Anagram (#242)",
    mistake: "Used HashMap with heavy boxing overhead in Java instead of fixed size int[26] frequency array.",
    correctPattern: "Fixed Array Frequency Counting",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    keyLearning: "For ASCII lowercase letters, int[26] is 10x faster and requires 0 memory allocation compared to HashMap.",
    dateLogged: "2026-08-26",
  },
];

export const WEEKLY_LEADERBOARD_SAMPLE = [
  { rank: 1, name: "Vignesh R.", problems: 42, streak: "18 Days 🔥", avatar: "VR", tier: "Advanced" },
  { rank: 2, name: "Priya S.", problems: 38, streak: "14 Days 🔥", avatar: "PS", tier: "Advanced" },
  { rank: 3, name: "Karthik K.", problems: 35, streak: "12 Days 🔥", avatar: "KK", tier: "Intermediate" },
  { rank: 4, name: "You (Student)", problems: 31, streak: "12 Days 🔥", avatar: "ME", tier: "Intermediate", isCurrentUser: true },
  { rank: 5, name: "Ananya M.", problems: 28, streak: "9 Days 🔥", avatar: "AM", tier: "Intermediate" },
  { rank: 6, name: "Dinesh B.", problems: 24, streak: "7 Days 🔥", avatar: "DB", tier: "Beginner" },
];
